ARG MLFLOW_VERSION=3.10.1
FROM ghcr.io/mlflow/mlflow:v${MLFLOW_VERSION}

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir \
    psycopg2-binary \
    boto3 \
    flask-wtf

COPY basic_auth.ini /app/basic_auth.ini

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0"]
